# Generated by Django 4.1.7 on 2023-03-28 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='has_children',
        ),
    ]
